/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119264-g2229b74127-20250415"
#endif /* AVUTIL_FFVERSION_H */
